### ISSUE TITLE
Stuck on preparing payment

### ISSUE THREAD

**Issue by sutho100** [snipcart/snipcart-v3-feedback#31] opened 2019-10-25 21:21 UTC
**Integration URL**
http://toddsutherlanddesigns.com/sophie/

**Describe the bug**
testing updated snipcart V3, after filling out the required address snipcart go to the second step of 'preparing payment' it gets stuck in a loading screen https://payment.snipcart.com/api/public/sessions

it happens on this post request 
https://payment.snipcart.com/api/public/sessions
there's no errors and has a  'Status Code: 201 Created'

**Expected behavior**
continue on to the payment options

**Screenshots**
![image](https://user-images.githubusercontent.com/19797335/67605210-6cf51900-f7c9-11e9-9362-adc64897a676.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 77

**Comment by thatfrankdev** [comment] 2019-10-25 23:06
Hi there,

Thanks for reporting this. I see there is no payment method available on the payment session you initiated. It may be the cause of the ever loading payment screen. We'll investigate and work on a fix ASAP.

Cheers!

**Comment by jacklinwood** [comment] 2019-12-13 10:05
Getting the same issue.

Was this ever resolved?

**Comment by JeanSebTr** [comment] 2019-12-16 18:55
Hey @jacklinwood !

Those issues are dependant on account configurations. We're in the process of improving error messages to make them easier to diagnose.

If anybody gets this error, please open a conversation with the support on Intercom, we'll be able to help more specifically.

**Comment by jacklinwood** [comment] 2019-12-16 20:54
Thanks for getting back to me.

Snipcart has support? Where can this be accessed?

**Comment by JeanSebTr** [comment] 2019-12-16 22:28
@jacklinwood Intercom widget in the dashboard:
![image](https://user-images.githubusercontent.com/867435/70948368-592b9d80-2029-11ea-9da3-69091b72a065.png)

Or by email `geeks@snipcart.com` or by replying to any of our automated email 🙂

**Comment by JeanSebTr** [comment] 2020-02-03 17:10
Situations, where the cart gets stuck in a loading state, should be [fixed in 3.0.6](https://docs.snipcart.com/v3/release-notes). You should now get an error message.

We'll provide more detailed feedback for developers in Test Mode in future releases about specific issue (crawling, configuration error, ...) with appropriate help text based on the error.

**Closed by JeanSebTr** 2020-02-03 17:10 UTC
Labels: bug, planned
