### ISSUE TITLE
Billing form displaying incorrectly 

### ISSUE THREAD

**Issue by julianms** [snipcart/snipcart-v3-feedback#41] opened 2019-11-12 22:11 UTC
**Integration URL**
https://shiftinglight.com/shop/

**Describe the bug**
The billing form fields and labels are not aligned, the zip code and apt/suite fields are overlapping the edge of the form field. 

**To Reproduce**

**Expected behavior**
I can see what it should look like from the docs: https://docs.snipcart.com/v3/setup/customization

**Screenshots**
1.safari
![Screenshot 2019-11-12 at 22 57 56](https://user-images.githubusercontent.com/8612017/68714529-50662880-05a0-11ea-841c-b0f45cfdf74b.png)
2. firefox
![Screenshot 2019-11-12 at 23 03 54](https://user-images.githubusercontent.com/8612017/68714758-cec2ca80-05a0-11ea-9044-29ecc1725e46.png)

It is the same on a android 9 

**Desktop (please complete the following information):**
 - OS: Mac 10.15.1
 - Browsers : chrome Version 78.0.3904.97 /safari 13.0.3/ firefox 70.0.1
   

**Smartphone (please complete the following information):**
 - Device:samsung s9
 - OS: android 9
 - Browser chrome
 

**Additional context**

**Comment by JeanSebTr** [comment] 2019-11-12 22:25
Hi @julianms !

This appears to be caused by those CSS rules:
![image](https://user-images.githubusercontent.com/867435/68715997-36f9b800-0571-11ea-885e-dc2f1d842d32.png)

We'll try to make our CSS more resilient to external styles, but in the meantime, you can change the specificity of your selector to not affect the cart.

**Comment by JeanSebTr** [comment] 2020-02-03 17:05
I'll close this issue as it's specific to your integration.

We'll be working on improving potential CSS collisions eventually.

**Closed by JeanSebTr** 2020-02-03 17:05 UTC
Labels: bug
